name: CI

on:
  # schedule:
   # - cron: "*/60 * * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  macos:
    name: "Run on the fastest infrastructure"
    runs-on: warp-macos-latest-arm64-6x
    steps:
      - uses: actions/checkout@v3
      - name: Version
        run: ls -l /dev/*tart-version-*
