name: CI

on:
  # schedule:
   # - cron: "*/60 * * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  macos:
    name: "Run on the fastest infrastructure"
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: printenv
